all:
  hosts:
  children:
    zabbix:
      hosts:
        {{public_dns}}
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /home/igor/Documentos/aws/aws-ec2-server.pem # Change needed
        ansible_become: yes
        ansible_port: 22
