---
- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Only run update
  apt:
    update_cache: yes
    upgrade: yes

- name: Add an Apt signing key zabbix
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Ubuntu"
  with_items:
    - deb-src
    - deb

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Debian"
  with_items:
    - deb-src
    - deb
    
- name: Remove apache
  apt:
    name: apache2
    state: absent

- name: Ensure a locale exists
  locale_gen:
    name: en_US
    state: present
  when:
    - ansible_distribution == 'Debian' 

- name: php-pgsql | Install Zabbix packeges
  apt:
    name: php7.4-pgsql
  when:
    - zabbix_server_database == 'pgsql'

- name: Copy php.zabbix.conf template 
  template:
    src: zabbix-php.conf.j2
    dest: /etc/zabbix/php-fpm.conf

- name: Make sure php service is running
  systemd:
    name: php7.4-fpm
    state: restarted
    enabled: yes
  when: 
    - ansible_distribution_file_variety == 'Debian' and ansible_distribution_major_version <= '20'